.catalog:
  name: "DataDog"
  version: "11.0.563-rancher1"
  description: "Datadog Agent and DogStatsD"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: "api_key"
      label: "DataDog Api Key"
      description: "Your DataDog API key"
      required: true
      type: "string"
    - variable: "host_labels"
      label: "Host Labels to Tags"
      description: |
        Comma delimited list (no spaces) of host labels to set as DataDog key/value tags.
        Example: 'provider,region'
      required: false
      type: "string"
    - variable: "global_service"
      label: "Global Service"
      description: |
        Enable this option to run an instance of the DataDog Agent on every host.
        If you merely want a StatsD aggregator to which other services can send
        metrics, then you may uncheck this and instead enable the Standalone mode.
      required: true
      type: "boolean"
      default: true
    - variable: "statsd_standalone"
      label: "Standalone StatsD"
      description: |
        Enable this option to run only DogStatsD without the full Agent.
        You can then send StatsD metrics to port 8125/udp of the service.
      required: true
      type: "boolean"
      default: false
    - variable: "statsd_namespace"
      label: "StatsD Metric Namespace"
      description: |
        You may optionally set a namespace for all StatsD metrics aggregated by this service.
        If set then 'metric.name' will become 'namespace.metric.name'.
      required: false
      type: "string"
