elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - ${es_port}:9200
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - ${kibana_port}:5601
  links:
    - elasticsearch
fluentd:
  build: fluentd/
  volumes:
    - /var/lib/docker/containers:/var/lib/docker/containers
  links:
    - elasticsearch
  ports:
    - ${fluentd_port}:24224
nginx:
  build: nginx/
  links:
    - fluentd
    - node_app
  ports:
    - ${nginx_port}:80
  log_driver: 'fluentd'
  log_opt:
    fluentd-address: localhost:24224
    fluentd-tag: docker.{{.FullID}}
node_app:
  build: node_app/
  links:
    - fluentd
  ports:
    - ${nodeapp_port}:8080
  log_driver: 'fluentd'
  log_opt:
    fluentd-address: localhost:24224
    fluentd-tag: docker.{{.FullID}}