alfresco:
  environment:
    CIFS_ENABLED: 'false'
    FTP_ENABLED: 'false'
  labels:
    io.rancher.container.pull_image: always'
  tty: true
  image: webcenter/rancher-alfresco:v5.1.0-2
  links:
  - postgres:db
  stdin_open: true
  ports:
  - 8080:8080/tcp
postgres:
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: ${database_name}
    POSTGRES_PASSWORD: ${database_password}
    POSTGRES_USER: ${database_user}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: postgres:9.4
  stdin_open: true
