.catalog:
  name: kali
  version: latest
  description: |
    Kali base image.
  minimum_rancher_version: v0.56.0
  maintainer: "Michael Wan <onehao333@gmail.com>"
  questions:    
    - variable: ssh_port
      description: "ssh port to access the kali"
      label: "ssh Port"
      required: true
      default: "8122"
      type: "int"  
    - variable: vnc_port
      description: "vnc port to access the kali"
      label: "vnc Port"
      required: true
      default: "5901"
      type: "int"

