name: Datadog
description: |
  Real-time performance tracking and visualization of your container-based application deployment
version: 11.0.570-rancher1
category: Monitoring
maintainer: "Jan Broer <jan@festplatte.eu.org>"
license: The MIT License
