wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - ${public_port}:80
  labels:
    io.rancher.scheduler.affinity:host_label: type=real
  net: bridge

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
  labels:
    io.rancher.scheduler.affinity:host_label: type=real
  net: bridge


db:
  image: mysql:5.7
  volumes:
    - "./.data/db:/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
  labels:
    io.rancher.scheduler.affinity:host_label: type=real
  net: bridge

wordpress:
  image: wordpress:latest
  links:
    - db
  ports:
    - ${public_port}:80
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_PASSWORD: wordpress
  labels:
    io.rancher.scheduler.affinity:host_label: type=real
  net: bridge