wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - ${public_port}:80
  labels:
    io.rancher.scheduler.affinity:host_label: type=real
  log_driver: 'fluentd'
  log_opt:
    fluentd-address: onehao.pw:24224
    fluentd-tag: docker.{{.FullID}}s

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
  labels:
    io.rancher.scheduler.affinity:host_label: type=real
  log_driver: 'fluentd'
  log_opt:
    fluentd-address: onehao.pw:24224
    fluentd-tag: docker.{{.FullID}}
