name: Sematext Docker Agent
description: |
  Sematext Docker Agent - Performance Monitoring. Collection of Metrics, Events and Logs. 
version: 1.29.44
category: Monitoring
maintainer: "Stefan Thies <stefan.thies@sematext.com>"
license: APACHE 2.0
